### ISSUE TITLE
support wrap attribute based on the count of attributes

### ISSUE THREAD

**Issue by pycodev** [Prettyhtml/prettyhtml#62] opened 2018-10-31 04:21 UTC
based on the count of tag's attributes, decide whether to wrap attribute.

thx :)

**Comment by StarpTech** [comment] 2018-10-31 07:49
Is this a duplicate of https://github.com/Prettyhtml/prettyhtml/issues/45? When not, please use the proposal issue template to describe your expectations in detail.

**Closed** 2018-11-08 22:15 UTC
