### ISSUE TITLE
Problems with tables

### ISSUE THREAD

**Issue by tao-cumplido** [Prettyhtml/prettyhtml#27] opened 2018-09-10 13:55 UTC
I encountered some problems with tables. I have two components `my-table` and `my-row`.

The template for `my-table` is like this:
```html
<table>
  <tbody><ng-content select="my-row"></ng-content></tbody>
</table>
```
One pf the problems is that `ng-content` gets extracted from the `table` tree, i.e. the output is like this:
```html
<ng-content select="my-row"></ng-content>
<table>
  <tbody></tbody>
</table>
```
The other problem I encountered is when I actually use `my-table` in another template:
```html
<my-table>
  <my-row>
    <td>foo</td>
    <td>bar</td>
  </my-row>
</my-table>
```
prettyhtml strips the `td` elements:
```html
<my-table>
  <my-row>
    foo
    bar
  </my-row>
</my-table>
```

Version is 0.0.55

**Comment by StarpTech** [comment] 2018-09-10 21:14
Hi, thank you for checking out prettyhtml. I can reproduce it and the reason is parse5 (the internal used html parser) it parsed the content based on the current browser specifications.

I will investigate.

**Comment by StarpTech** [comment] 2018-09-12 22:02
Fixed with the latest update @starptech/prettyhtml 0.0.56

**Comment by StarpTech** [comment] 2018-09-15 08:35
Feel free to reopen the issue. I tested both cases and it works.

**Closed by StarpTech** 2018-09-15 08:35 UTC
